services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    networks: [ internal ]

  node:
    image: docker.sunet.se/te-canvas-front
    depends_on: [ mongo ]
    environment:
      - LTI_URL
      - API_URL=http://api:5000

      - MONGO_URL=mongodb://mongo:27017
      - MONGO_USERNAME
      - MONGO_PASSWORD

      - PLATFORM_NAME
      - CLIENT_ID
      - ENCRYPTION_KEY
      - AUTHORIZED_ROLES
    networks: [ internal, external ]

networks:
  internal:
  external:
    external: true
