services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    networks: [ te-canvas ]

  node:
    build: .
    depends_on: [ mongo ]
    environment:
      - LTI_URL
      - API_URL

      - MONGO_URL=mongodb://mongo:27017
      - MONGO_USERNAME
      - MONGO_PASSWORD

      - PLATFORM_NAME
      - CLIENT_ID
      - LTI_KEY
    networks: [ te-canvas ]

  nginx:
    image: nginx
    volumes:
      - ./nginx-docker.conf:/etc/nginx/nginx.conf
      - ./localhost.crt:/etc/nginx/localhost.crt
      - ./localhost.key:/etc/nginx/localhost.key
    networks: [ te-canvas ]
    ports: [ 127.0.0.1:443:443 ]

networks:
  te-canvas:
    external: true
