services:
  mongo:
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "$MONGO_USERNAME"
      MONGO_INITDB_ROOT_PASSWORD: "$MONGO_PASSWORD"
    ports:
      - "127.0.0.1:27017:27017"
