services:

  mongo:
    logging:
      driver: local
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD

  node:
    logging:
      driver: local
    image: docker.sunet.se/te-canvas-front:${TAG_NODE-latest}
    depends_on: [ mongo ]
    environment:
      - LTI_URL

      - MONGO_URL=mongodb://mongo:27017
      - MONGO_USERNAME
      - MONGO_PASSWORD

      - ENCRYPTION_KEY
    volumes:
      - ./platforms.json:/usr/src/app/platforms.json
    networks: [ te-canvas, default ]

  nginx:
    logging:
      driver: local
    image: nginx
    depends_on: [ node ]
    volumes:
      - ./nginx-docker.conf:/etc/nginx/nginx.conf
      - ./ssl.crt:/etc/nginx/ssl.crt
      - ./ssl.key:/etc/nginx/ssl.key
      - ./lti.json:/www/data/lti.json
    ports: [ "${LTI_PORT}:443" ]

networks:
  te-canvas:
    external: true
