services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    networks: [ te-canvas ]

  node:
    image: docker.sunet.se/te-canvas-front
    depends_on: [ mongo ]
    environment:
      - LTI_URL
      - API_URL=http://api:5000

      - MONGO_URL=mongodb://mongo:27017
      - MONGO_USERNAME
      - MONGO_PASSWORD

      - PLATFORM_NAME
      - CLIENT_ID
      - ENCRYPTION_KEY
      - AUTHORIZED_ROLES
    networks: [ te-canvas ]

  nginx:
    image: nginx
    depends_on: [ node ]
    volumes:
      - ./nginx-docker.conf:/etc/nginx/nginx.conf
      - ./ssl.crt:/etc/nginx/ssl.crt
      - ./ssl.key:/etc/nginx/ssl.key
      - ./lti.json:/www/data/lti.json
    networks: [ te-canvas ]
    ports: [ 443:443 ]

networks:
  te-canvas:
