window.injectedEnv = {
    BACKEND_URL: "$LTI_URL", // NOTE: Special case
    API_URL: "$API_URL",

    MONGO_URL: "$MONGO_URL",
    MONGO_USERNAME: "$MONGO_USERNAME",
    MONGO_PASSWORD: "$MONGO_PASSWORD",

    PLATFORM_NAME: "$PLATFORM_NAME",
    CLIENT_ID: "$CLIENT_ID",
    LTI_KEY: "$LTI_KEY",
};
